data:
  data_source: "mongo" #mongo when using mongoDB
  uri: "mongodb://admin:secret@localhost:27017/"
plots:
  plot_1_defect:
    type: "single"
    average: False
    fix_y: False
  plot_2_defect:
    type: "heatmap"
    x: "interstitial"
    y: "substitution"
  plot_3_defect: #To get sub-sub. Dont think we have int-int
    type: "heatmap"
    x: "combined"
    y: "combined"
  plot_4_defect: #To get sub-sub. Dont think we have int-int
    type: "sub-sub"
    average: False