name: CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name : Checkout httk
        uses: actions/checkout@v4
        with:
          repository: httk/httk
          ref: v1.2.0
          path: httk-src

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ./httk-src
          pip install -e .
          pip install ruff

      - name: Run ruff check
        run: ruff check .

  test_example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name : Checkout httk
        uses: actions/checkout@v4
        with:
          repository: httk/httk
          ref: v1.2.0
          path: httk-src

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libopenmpi-dev openmpi-bin
          python -m pip install --upgrade pip
          pip install -e ./httk-src
          pip install -e .
          pip install pytest

      - name: Start MongoDB container
        run: |
          docker compose -f database/docker-compose.yaml up -d --build
          sleep 15  # Wait for MongoDB to be ready

      - name: Verify OPTIMADE connects
        run: |
          curl http://localhost:8000/v1/info
          curl http://localhost:8000/v1/structures

      - name: Validate OPTIMADE implementation
        uses: Materials-Consortia/optimade-validator-action@v2
        with:
          protocol: http
          domain: localhost
          port: 8000
          path: /
          all versioned paths: True

      - name: Run regular tests
        run: pytest -m "not mpi"

      - name: Run MPI tests
        run: |
          CORES=$(nproc --all)
          N=$(( CORES < 2 ? 1 : 2 ))
          echo "Running MPI tests with $N processes"
          mpirun --oversubscribe -n $N pytest -m mpi
