name: CI

on:
  push:
    branches: [ "main", "develop", "167-expand-integration-tests---5"]
  pull_request:
    branches: [ "main", "develop" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name : Checkout httk
        uses: actions/checkout@v4
        with:
          repository: httk/httk
          ref: v1.2.0
          path: httk-src

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ./httk-src
          pip install -e .
          pip install ruff

      - name: Run ruff check
        run: ruff check .

  test_example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libopenmpi-dev openmpi-bin
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest
        
      - name: Cache MACE model
        id: cache-mace
        uses: actions/cache@v3
        with:
          path: models/2023-12-10-mace-128-L0_energy_epoch-249.model
          key: mace-model-2023-12-10

      - name: Download MACE model if missing
        if: steps.cache-mace.outputs.cache-hit != 'true'
        run: |
          echo "Cache miss — downloading model..."
          mkdir -p models
          curl -L -o models/2023-12-10-mace-128-L0_energy_epoch-249.model \
            https://github.com/ACEsuit/mace-foundations/releases/download/mace_mp_0/2023-12-10-mace-128-L0_energy_epoch-249.model

      - name: Verify model presence
        run: |
          if [ ! -f models/2023-12-10-mace-128-L0_energy_epoch-249.model ]; then
            echo "ERROR: MACE model is missing!"
            exit 1
          fi
          echo "MACE model found."

      - name: Start MongoDB container
        run: |
          docker compose -f database/docker-compose.yaml up -d --build
          sleep 3  # Wait for MongoDB to be ready
      
      - name: Run regular tests
        run: pytest -m "not mpi"

      - name: Run MPI tests
        run: |
          CORES=$(nproc --all)
          N=$(( CORES < 2 ? 1 : 2 ))
          echo "Running MPI tests with $N processes"
          mpirun --oversubscribe -n $N pytest -m mpi
